### PR TITLE
New QA check for accesUrl

### PR DESCRIPTION
**Pull request by SolomonShorser-OICR**
This PR should not be merged until the `resourceIdentifier` attribute is added to the `ReferenceDatabase` object type, and populated.

### CODE REVIEW

**Comment by SolomonShorser-OICR** [comment]
@guanmingwu This PR depends on a new attribute, "resourceIdentifier", existing on the ReferenceDatabase type. This PR should not be merged until that attribute has been created.

**Comment by guanmingwu** [comment]
The new attribute resourceIdentifier has been in gk_central and should be pulled out automatically into the slice database. I have added a new Java constant org.gk.model.ReactomeJavaConstants. However, I have not update the maven jar for it. Need to find out how.

**Comment by SolomonShorser-OICR** [comment]
@guanmingwu Please let me know what new version is, once has been deployed to maven central. Also, what is the name of the new property in `ReactomeJavaConstants`?

**Comment by guanmingwu** [comment]
Please use this: 2.1.0-SNAPSHOT. The new constant name is the same attribute name as always: resourceIdentifier. By the way, this is just a String constant.

**Comment by SolomonShorser-OICR** [comment]
@guanmingwu Is this OK to merge?

**Comment by guanmingwu** [comment]
Yes. Please.

**Pull request merged**
