### PR TITLE
README edit.

### PR DESCRIPTION
**Pull request by lbeckman314**
Hi! I'm just getting familiarized with the `release-qa` code base. This is just a small spelling edit to `README.md` as I get started with working on it!

### CODE REVIEW

**Comment by jweiser** [comment]
> Hi! I'm just getting familiarized with the `release-qa` code base. This is just a small spelling edit to `README.md` as I get started with working on it!

Hi Liam!  Sure, do you want a review on this PR?

**Comment by jweiser** [comment]
> Hi Joel! A review would be great. This commit is only two edits, so may not warrant one, but future commits will probably be more meaningful!

Hi Liam - sure, whenever you'd like feedback, feel free to tag us for reviews through GitHub's request mechanism.  This PR looks good!  I was just wondering why the "target" directory was removed from the .gitignore file, though?

**Comment by lbeckman314** [comment]
Awesome -- I will tag away!

> This PR looks good! I was just wondering why the "target" directory was removed from the .gitignore file, though?

Oh my mistake! I think that was me removing it after mistakenly adding it in the previous [commit](https://github.com/reactome/release-qa/pull/14/commits/43f23dc647d4a6aaa498ca0aedb6c73f6767dd25).

**Comment by jweiser** [comment]
> Awesome -- I will tag away!
> 
> > This PR looks good! I was just wondering why the "target" directory was removed from the .gitignore file, though?
> 
> Oh my mistake! I think that was me removing it after mistakenly adding it in the previous [commit](https://github.com/reactome/release-qa/pull/14/commits/43f23dc647d4a6aaa498ca0aedb6c73f6767dd25).

Ah, okay!  I'm sorry - I think it was actually my misunderstanding.  I thought the .gitignore file was being changed relative to the master branch by that commit.  I was wondering why .gitignore did not appear in the "File changed" tab!  The PR looks good to me!

**Pull request merged**
